# Generated by Django 5.0.1 on 2024-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('SM', 'Small Pasta'), ('RC', 'Ribbon-Cut'), ('TS', 'Tube-Shaped'), ('ST', 'Stuffed')], default='SM', max_length=2)),
                ('cook_time', models.IntegerField()),
            ],
        ),
    ]
