# Generated by Django 5.0.1 on 2024-01-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='type',
            field=models.CharField(choices=[('SM', 'Small Pasta'), ('Ribbon-Cut', 'Ribbon-Cut'), ('TS', 'Tube-Shaped'), ('ST', 'Stuffed')], default='SM', max_length=20),
        ),
    ]
