# Generated by Django 5.0.1 on 2024-01-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pasta_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='type',
            field=models.CharField(choices=[('Small Pasta', 'Small Pasta'), ('Ribbon-Cut', 'Ribbon-Cut'), ('Tube-Shaped', 'Tube-Shaped'), ('Stuffed', 'Stuffed')], default='Small Pasta', max_length=20),
        ),
    ]
