# Generated by Django 5.0.1 on 2024-01-12 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_pasta_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('is_vegetarian', models.BooleanField()),
                ('recipe_link', models.URLField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('D', 'Difficult')], default='M', max_length=1)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pasta')),
            ],
        ),
    ]
