# Generated by Django 5.0.1 on 2024-01-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['difficulty']},
        ),
        migrations.AlterField(
            model_name='dish',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('D', 'Difficult')], default='M', max_length=1, verbose_name='cook difficulty'),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='type',
            field=models.CharField(choices=[('SM', 'Small Pasta'), ('RC', 'Ribbon-Cut'), ('TS', 'Tube-Shaped'), ('ST', 'Stuffed')], default='SM', max_length=2),
        ),
    ]
